fix 1.20.2 can not view skin
yushijinhun/authlib-injector pull request #226
Opened 2023-10-14 16:39 UTC by xmdhs

1.20.2 更新了 authlib 版本，并把 `getSignature` 和 `getValue` 方法改名成 `signature` 和 `value`。且 net.minecraft.client.resources.SkinManager 中改成了默认获取带有签名的皮肤，导致在 1.20.2 无法加载皮肤。

这个 pr 尝试修复这个问题，我对于 javaagent 不是很了解，这样判断应该有些问题。我自己的测试中皮肤是已经可以加载，服务器中也是。

2023-10-15 14:01 UTC, xfl03 requested changes
不能默认`isSignatureValid`方法一定在`signature`后面被visit

2023-10-15 14:59 UTC, xmdhs commented
改成为 Property 添加回 getter，麻烦看看有什么问题

2023-10-16 03:29 UTC, xfl03 approved these changes

2023-10-17 18:22 UTC, HongYunCloud requested changes

2023-10-17 18:22 UTC, HongYunCloud commented on src/main/java/moe/yushi/authlibinjector/transform/support/YggdrasilKeyTransformUnit.java
> +					if ("value".equals(name)) {
```suggestion
					"value".equals(name) && "()Ljava/lang/String;".equals(desc)
```

2023-10-17 18:22 UTC, HongYunCloud commented on src/main/java/moe/yushi/authlibinjector/transform/support/YggdrasilKeyTransformUnit.java
> +					if ("signature".equals(name)) {
```suggestion
					"signature".equals(name) && "()Ljava/lang/String;".equals(desc)
```

2023-10-17 18:22 UTC, HongYunCloud commented on src/main/java/moe/yushi/authlibinjector/transform/support/YggdrasilKeyTransformUnit.java
> +						mv.visitMaxs(1, 1);
```suggestion
						mv.visitMaxs(-1, -1);
```
COMPUTE_MAXS enabled

2023-10-17 18:22 UTC, HongYunCloud commented on src/main/java/moe/yushi/authlibinjector/transform/support/YggdrasilKeyTransformUnit.java
> +						mv.visitMaxs(1, 1);
```suggestion
						mv.visitMaxs(-1, -1);
```
COMPUTE_MAXS enabled

2023-11-01 11:18 UTC, yushijinhun commented
Thank you for the pull request. I've actually implemented a different solution to address the bug (https://github.com/yushijinhun/authlib-injector/commit/f6970a51b2b1974b90e43d3786e55dcef04d6a8e).

2023-11-01 11:18 UTC, closed without merging